accounts:
  - name: alice
    coins: ["20000000000hrsh", "200000000stake"]
  - name: bob
    coins: ["10000000000hrsh", "100000000stake"]
validator:
  name: alice
  staked: "10000000stake"
client:
  openapi:
    path: "docs/static/openapi.yml"/
faucet:
  name: bob
  coins: ["5hrsh", "100000stake"]
