accounts:
  - name: alice
    coins: ["100000000stake"]
  - name: bob
    coins: ["100000000stake"]
validator:
  name: alice
  staked: "10000000stake"
client:
  openapi:
    path: "docs/static/openapi.yml"
faucet:
  name: bob
  coins: ["100000stake"]
